apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
     app: flask
     type: front-end
spec:
  template:
     metadata:
       name: flask-app
       labels: 
         app: flaskapp
         type: front-end
     spec:
         containers:
           - name: myflaskapp
             image: "jw124210/flaskapp:1.2"
  replicas: 1
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flaskapp
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 5000
      nodePort: 30000
